version: "3.8"
services:
  postgresql:
    image: postgres:15.1
    container_name: sqlx-postgresql-schemas
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
